# Creates a GitHub Release.
# Workflow is manually run.
# Preselect branch or tag before running this workflow.
name: release

on:
  workflow_dispatch:
    inputs:
      nightly:
        description: "Mark as nightly build"
        required: true
        default: true
        type: boolean
      dogorelease:
        description: "Run goreleaser"
        required: true
        default: true
        type: boolean
      dodistrelease:
        description: "Release distribution source tarball"
        required: true
        default: true
        type: boolean
      dodebrelease:
        description: "Release DEB packages in APT repository"
        required: true
        default: true
        type: boolean
      dorpmrelease:
        description: "Release RPM packages in YUM repository"
        required: true
        default: true
        type: boolean

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release-main:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
      SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES: "true"
      SYFT_GOLANG_SEARCH_REMOTE_LICENSES: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Configure nightly build
        if: inputs.nightly
        run: |
          git remote add upstream https://github.com/openbao/openbao
          git fetch --all

          for tag in $(git tag); do
            if [[ "$tag" == *nightly* ]]; then
              echo "Deleting $tag"
              git tag --delete "$tag"
            fi
          done

          nightly_tag="$(bash ./scripts/nightly_tag.sh)"
          git tag "$nightly_tag"

      - name: Golang Setup
        uses: ./.github/actions/set-up-go

      - name: go-check
        run: go version

      # Supports syft/sbom generation
      - name: Install Syft
        uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0

      - name: Verify Syft
        run: syft version

      - name: Generate SBOM (SPDX JSON)
        run: |
          mkdir -p dist

          syft scan . \
            -o spdx-json=dist/openbao.spdx.json

      - name: Generate SBOM (CycloneDX JSON)
        run: |
          syft scan . \
            -o cyclonedx-json=dist/openbao.cdx.json

      - name: Generate SBOM (Syft JSON)
        run: |
          syft scan . \
            -o syft-json=dist/openbao.syft.json

      - name: List generated SBOMs
        run: ls -lh dist/

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: dist/*.json
          retention-days: 7
