# Creates a GitHub Release.
# Workflow is manually run.
# Preselect branch or tag before running this workflow.

name: release

on:
  workflow_dispatch:
    inputs:
      nightly:
        description: "Mark as nightly build"
        required: true
        default: true
        type: boolean

      dogorelease:
        description: "Run goreleaser"
        required: true
        default: true
        type: boolean

      dodistrelease:
        description: "Upload release artifacts"
        required: true
        default: false
        type: boolean

permissions:
  contents: write
  packages: write

env:
  GO_VERSION: "1.24"

jobs:
  gorelease:
    name: goreleaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Prepare Go dependencies
        run: |
          go mod tidy
          go mod download
          go mod vendor

      - name: Verify licenses resolve
        env:
          SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES: "true"
          SYFT_GOLANG_SEARCH_LOCAL_VENDOR_LICENSES: "true"
          SYFT_GOLANG_SEARCH_REMOTE_LICENSES: "true"
          SYFT_GOLANG_PROXY: "https://proxy.golang.org,direct"
        run: |
          syft dir:. -o spdx-json=sbom.spdx.json

          echo "==== SPDX LICENSE CHECK ===="
          jq '.packages[] | select(.licenseConcluded != "NOASSERTION") | {name, licenseConcluded}' sbom.spdx.json | head -50

      - name: Run GoReleaser
        if: ${{ inputs.dogorelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # SPDX / license detection
          SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES: "true"
          SYFT_GOLANG_SEARCH_LOCAL_VENDOR_LICENSES: "true"
          SYFT_GOLANG_SEARCH_REMOTE_LICENSES: "true"
          SYFT_GOLANG_PROXY: "https://proxy.golang.org,direct"

        run: |
          EXTRA_ARGS=""

          if [[ "${{ inputs.nightly }}" == "true" ]]; then
            EXTRA_ARGS="${EXTRA_ARGS} --nightly"
          fi

          goreleaser release \
            --clean \
            --skip=publish \
            ${EXTRA_ARGS}

      - name: Upload artifacts
        if: ${{ inputs.dodistrelease }}
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            dist/*
